### ISSUE TITLE
Extract codeblock for any language

### ISSUE THREAD

**Issue by danbeam** [earldouglas/codedown#29]
I would like to extract a codeblock that doesn't have a language e.g. just ` ``` ` and not ` ```javascript `.

As far as I know, that's not currently possible.  If it is and I simply haven't found how to do it: please let me know!

Otherwise: I was thinking a language parameter of `*` instead of e.g. `javascript` could maybe work.  The exact API for how this would be accomplished isn't critical, though.

**Comment by agardnerIT** [comment]
Thanks for this great tool! It's precisely what I was looking for (and about to code up myself) so you've just saved me lots of time!

FYI `*` doesn't work on the online example page.

**Comment by danbeam** [comment]
> Thanks for this great tool! It's precisely what I was looking for (and about to code up myself) so you've just saved me lots of time!
> 
> FYI `*` doesn't work on the online example page.

Did you use `*` or `'*'` in your shell command? `*` (no quotes) would likely expand to the files/directories in the current working directory (and probably would not work).

**Comment by earldouglas** [comment]
@agardnerIT Thanks for letting me know!  The online example page was using an old version of Codedown.  I updated it to the latest, and `*` is now working.
